name: Build gh-pages
on: [push]
jobs:
  build-process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      working-directory: ./my-app
      run: npm install
    - name: Config Credentials
      run: git config user.email "felixschreyer@mailbox.org"
           git config user.name "FelixSchreyer"
    - name: Build page
      working-directory: ./my-app
      run: npm run deploy
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build
