name: Build & deploy

on:
  push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: create CNAME
      uses: "finnp/create-file-action@master"
      with:
        working-directory: ./my-app
      env:
        FILE_NAME: "fileName.txt"
        FILE_DATA: "file content"
