name: Build & deploy

on:
  push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: create CNAME
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "fileName.txt"
        FILE_DATA: "file content"
